require("core.plugin-configs.lualine")
require("core.plugin-configs.nvim-tree")
require("core.plugin-configs.treesitter")
require("core.plugin-configs.textobject")
require("core.plugin-configs.luasnip")
require("core.plugin-configs.telescope")
require("core.plugin-configs.bufferline")
require("core.plugin-configs.comment")
require("core.plugin-configs.prettier")
require("core.plugin-configs.lastplace")
require("core.plugin-configs.indent-line")
require("core.plugin-configs.colorizer")
require("core.plugin-configs.toggleterm")
require("core.plugin-configs.nvim-surround")
require("core.plugin-configs.ufo")


